# Generated by Django 4.1.1 on 2022-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField(max_length=9)),
                ('hobbies', models.TextField()),
                ('email_verified', models.BooleanField(default=False)),
                ('telephone_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Register',
            },
        ),
    ]
