# Generated by Django 4.1.1 on 2022-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
